services:
  database:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./../content_service/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_CREATE_DB_CONTENT_SERVICE=content_service
  app-content:
    build:
      context: ./../content_service/ # necessary because otherwise docker-compose overrides the context when merging multiple docker-compose.yml files
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: content_service
    expose:
      - 4000
      - 4001
    ports:
      - "4000:4000"
      - "4001:4001"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/content_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  dapr-content:
    image: "daprio/daprd"
    command: [
      "./daprd",
      "--app-id", "content_service",
      "--app-port", "4001",
      "--dapr-http-port", "4000",
      "--resources-path", "./components"
    ]
    volumes:
      - "./../content_service/components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - app-content
      - redis
    network_mode: "service:app-content"
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  dbdata:
  testdata:
networks:
  default:
    name: dapr-network
    external: true